### ISSUE TITLE
Isn't compatible with ngx-i18nsupport

### ISSUE THREAD

**Issue by Andrey-Pavlov** [DavidOndrus/xliff-translator-tool#12]
@DavidOndrus  I'm trying to use https://github.com/martinroob/ngx-i18nsupport for merge updates in xlf files:

- it shows in ngx-i18nsupport for xlifmerge : The value "utf-16" is invalid for option "encoding" (xliff-translator-tool doesn't save source encoding UTF-8)
- it doesn't save the same xml structure
```
      <trans-unit id="app_logout">
        <source>Logout</source>
        <target>Выйти</target>
                <context-group purpose="location">
                        <context context-type="sourcefile">app/app.component.html</context>
                        <context context-type="linenumber">17</context>
                </context-group>
        </trans-unit>
```
```
      <trans-unit id="app_logout">
        <source>Logout</source>
        <target>Выйти</target>
      </trans-unit>
```

**Comment by DavidOndrus** [comment]
Hi, I do not have an experience with the tool you mentioned but that error with encoding is caused by file being saved in UTF-16 but I have no idea why. I've already explained it few months ago in another issue which you also commented. 

My tool won't try to keep original XML structure so some elements can be lost. It's stated in the project's README: "WARNING: This tool also removes all unnecessary elements from XLIFF file such as "location" of translation in source code."

**Comment by Andrey-Pavlov** [comment]
@DavidOndrus Sad panda

**Comment by DavidOndrus** [comment]
possible fix in fork https://github.com/JaronPiet/xliff-translator-tool
