### ISSUE TITLE
No in-place save

### ISSUE THREAD

**Issue by Hubble1942** [DavidOndrus/xliff-translator-tool#5]
Is there a specific reason on why there is only a 'Save as' but no 'Save' option?

**Comment by DavidOndrus** [comment]
Yes there is. It's a safety precaution.
Altought this is my own utility I must say that you can't completely trust it. It applies for all 3rd party utilies working with files. Simply there is a high chance you don't have backup of your original file. Since it doesn't completely copy original file's content but instead creates own data structure (based on official XLIFF format specification or at least, XLIFF format generated by Angular's xi18n tool), it's not a good idea to save to the original file.
Next 2 problems are filename and a feature allowing you to combine XLIFF 1.2 and XLIFF 2.0 formats.
You open file "1.xlf" (XLIFF format 1.2) and import "2.xlf" (XLIFF format 2.0). Which filename (filepath) and which format should this utility use for "Save" ?

Despite these questionable problems I decided to implement Save function. It uses the last file as a source of the information about XLIFF format version and filename (filepath).
You can find it in the latest version 1.3
